### ISSUE TITLE
Waiting for token network registration misses response check

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#125]
When waiting for the token network to be discovered by the raiden nodes, there are two bugs which need to be taken care of:

The requested node is also the node we registered the token with - on fast connections, this returns a 200 OK, giving us the impression that the nodes already discovered the token network - which is false. **Token network discovery must be checked on a node different from the node used to register the token**.

Secondly, any response from the API causes the `while` loop to exit, since the API returns an APIError, which has a JSON payload (`{"errors": <error>}`). This payload is assigned to `self.token_network_address` and the SP never checks its value. This results in the faulty address being propagated downstream and blow up only after the tasks have already been started. **The loop waiting for token network discovery MUST check the returned value, and continue waiting if it's a `404`** - ensure this is *not* an infinite wait.

Source of all evil:
https://github.com/raiden-network/scenario-player/blob/12db4ec8f9037dd418ac10e8cb74780ff613008f/scenario_player/runner.py#L210:L222

Related REST API Endpoint:
https://github.com/raiden-network/raiden/blob/f034b2d001f31bfb00c334dfc4eed69f275153ea/raiden/api/rest.py#L780:L797

Logs supplied by @agatsoh (See line L670 for error message, and note how SP frolickingly continues on to its doom.) :
https://pastebin.com/kMf1Rwff

**Comment by hackaugusto** [comment]
> Token network discovery must be checked on a node different from the node used to register the token

This should be done for every node that is being used in the scenario for that token network.

**Comment by nlsdfnbch** [comment]
Fixed with #126
