### ISSUE TITLE
Getting all scenarios run on the same token network - congestion

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#127]
# Domain of the Service
At the moment all scenarios run with new token networks that are deployed every time. At the moment we count 220 Token Networks on Görli (where we run most of the scenarios). 

**The problem:** The Raiden Client reads all the token networks into its database before startup. Starting up in Görli takes up to 5 minutes at the moment. 

Can we run all the scenarios in one token network?  That would also reflect our current plans on mainnet better (we will have only two bigger token networks)

In the scenarios, you can already define a specific token. We could, therefore, create another faucet on Görli with the SPT (ScenarioPlayerToken) and every time a scenario runs, it will get tokens from there.

**Comment by christianbrb** [comment]
Isn't this fixed now?

**Comment by Dominik1999** [comment]
yes long time ago
