### ISSUE TITLE
Add Basic Functionality scenario

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#135]
According to the spreadsheet where we have defined scenarios, we want to have a scenario that tests all the basic functionality of the Raiden API together and that goes through the happy path life cycle of a small token network.

**Comment by czepluch** [comment]
PR has been opened here: https://github.com/raiden-network/raiden/pull/4499

We also need to add it to the list of scenarios being run, once it's been merged.

**Comment by Dominik1999** [comment]
closed by https://github.com/raiden-network/raiden/pull/4499
