### ISSUE TITLE
Add withdraw task to scenarios

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#145]
#### Requirement
After the implementation of #136 is done, we should add the withdraw tasks to the scenarios because

- PFS -> Update capacity
- MS -> Update balance proof

#### Tasks
- [ ] Define, where it is necessary to add it
- [ ] Implement

CC @Dominik1999 @czepluch

**Comment by Dominik1999** [comment]
Thank you @christianbrb 
here is a sheet created by Jacob that defines what we want to test - also with respect to `withdraw`. 
[see here](https://docs.google.com/spreadsheets/d/1Mbjgp3X-VouhkbnCN5EogzWo2VqlsTfy0NcpTSaZiik/edit#gid=1806867935)

We want to test `withdraw` as part of the basic functionalities and with own scenarios.

**Comment by christianbrb** [comment]
@Dominik1999 But it would also affect MS and PFS
- PFS -> Update capacity
- MS -> Update balance proof

**Comment by Dominik1999** [comment]
Yes, with every "state change" in the channel a capacity update or a new monitor request gets triggered, good point

**Comment by nlsdfnbch** [comment]
Related PR is merged and released. Starting with `v0.2.0` , the withdraw task is usable in scenarios.
@Dominik1999

**Comment by christianbrb** [comment]
Closing this as we defined a new set of scenarios (see #216)
