### ISSUE TITLE
Support scenario files using jinja2 templating

### ISSUE THREAD

**Issue by deepbrook** [raiden-network/scenario-player#15]
Some configurations require replacing when running them on a specific setup.

An example would be the `pfs-address` config value. When running a PFS locally, this is fine to be `http://localhost:6000` - however, if not hosting your own `pfs` instance on the local machine, a custom address is required. 

To avoid having to manually replace these values, allow using jinja template values and get try to get the values from somewhere else first, defaulting to the `localhost` address if not found.

For example, check if a `PFS_ADDRESS` variable is set in the current ENV

**Comment by palango** [comment]
This is implemented.
