### ISSUE TITLE
Run fast scenarios first

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#164]
Currently, the long-running scenarios (msx_*) are executed first. In order to quickly find issues and spend time on investigating them, it is usefull to run the short scenarios (pfsx_*) first.

**Comment by nlsdfnbch** [comment]
Updated the script at `/var/lib/scenario-player`  on the ci droplet, checking with next nightly run if this works as expected.

**Comment by nlsdfnbch** [comment]
nightlies ran as expected.
