### ISSUE TITLE
Allow empty config sections in the scenario yaml

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#169]
Currently the SP throws `TypeError: argument of type 'NoneType' is not iterable` when there is a setup parameter in a scenario file that is empty. For instance having `token:` with no content gives above error:

```
settings:
  ..
token: # results in `{"token": None}` when parsed by yaml loader
scenario:
  ..
```

Instead, this should be converted to an empty `dict`.

**Comment by nlsdfnbch** [comment]
Fixed with https://github.com/raiden-network/scenario-player/commit/4d75dada2a078d531d5d725929fad3e40f4cfb22
