### ISSUE TITLE
SP crash when calling "mint_token_if_balance_low"

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#175]
I have not been able to reproduce a situation where I am able to decide whether it happens everytime "mint_token_if_balance_low" is called or only sometimes. Needs some further investigation to figure this out.

The line of code where it fails is a call to the blockchain: https://github.com/raiden-network/scenario-player/blob/29184753ea955e0f82520b5f150be752ea884297/scenario_player/utils/legacy.py#L296

See https://github.com/raiden-network/scenario-player/issues/154 for example logs.

**Comment by christianbrb** [comment]
Closing this as it didn't happen again within the last runs
