### ISSUE TITLE
Test dev branch and make a new release

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#210]
### Description

Issue to keep track of making a new release to integrate

- Withdraw #136 
    - Basic functionality using withdraw #135 
- UI Bug #131 
- RPC Service #199 (Outscoped -> #208)

### Tasks
- [x] Testing
- [ ] Making a release

**Comment by nlsdfnbch** [comment]
Done!
https://github.com/raiden-network/scenario-player/releases/tag/v0.2.0
