### ISSUE TITLE
Building a scenario backlog and specify

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#216]
### Problem
We have identified, that we need to add additional scenarios. 

### Solution
- [x] Define a scenario backlog with a rough description of each scenario
- [x] Order the backlog by priority
- [x] Specify the most important scenarios
~~- [ ] Implement scenarios~~
- [x] Define which old scenarios need to be deleted

**Comment by Dominik1999** [comment]
Todo:
- Rewrite existing scenarios acc. to principles and delete PFS6
- PFS payment
- PFS routing constraints
- MS scenario changes
- Routing preferences (Needs new SP features)
 
Principles:
- always use `transfer` not `assert_pfs_routes`
- many small scenarios not big ones
- always with fees

Scenarios to be created (or use what is already there): - Just make sure that it is tested in small scenarios
PFS to be tested:
- **Payments**: 
-- payments (single) ~PFS7 scenario
-- payments (multiples)
- **Routing Constraints**:  
-- presence check: node goes offline during test
-- capacity updates (fixed topology, first pfs returns route, then capacity changes, then fewer routes are returned, no route) (1) withdraw (2) transfers -> test with mediating nodes 
- **Routing preferences** (probably new feature):
-- fees to be tested (this needs a new feature request). investigate if already possible 
-- routing preferences: (1) cheapest route (2) shortest route. requires fee setting in SP

MS to be tested:
- UDC Deposit is too low, then the MS should not intervene (Feature from Nils)
- Withdraw node sends MR then withdraws and then MS should get 2 MR

**Comment by christianbrb** [comment]
Created 4 new issues
#4590
#4591
#4592
#4593

**Comment by palango** [comment]
@eorituz Regarding the fee scenario(s):

A simple one I can image would be:
```
+--- 110 --> B --- 100 ---v
A                         C
+--- 100 --> D --- 100 ---^
```

In this case, with a flat fee of 10 and a payment value of 100, the PFS should only return the upper route.

The same kind of scenario could then be written with proportional fees

For the imbalance fees it would make sense to create two equal routes and then add imbalance and look that the routes get returned in a way that minimizes the fees.
