### ISSUE TITLE
Fee setting in SP

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#227]
Analysis
=======
Current State
-----------------
Raiden nodes now have mediation fee settings:
```
Mediation Fee Options:
  --flat-fee FEEAMOUNT            Flat fee required for every mediation in wei of the mediated token.  [default: 0]
  --proportional-fee INTEGER      Mediation fee as ratio of mediated amount in parts-per-million (10^-6).  [default:
                                  0]
  --max-imbalance-fee FEEAMOUNT   Set the worst-case imbalance fee in wei of the mediated token. (Preview)  [default:
                                  0]
```

Problem
-----------
The mediation fees are not settable in the scenario player. We need the mediation fees for the following scenario https://github.com/raiden-network/raiden/issues/4594

Solution
----------
Add the settings to the known settings options.

----------------------------------------------------------------------
User Stories
==========
*Describe the requested feature in user stories, describing one behavior at a time, with one story each. These are later used to test and assert the correctness of the feature, so be detailed and thorough when writing these. They may be updated later, during the course of the discussion of this issue.*

**Comment by eorituz** [comment]
The Fee Options are already available. 
You can set them in the `default-option` section of the Scenario yaml.
I'll add examples in the example file.

**Comment by christianbrb** [comment]
Waiting for PR #237 to be merged

**Comment by nlsdfnbch** [comment]
merged, @christianbrb
