### ISSUE TITLE
Increase test coverage of main.py

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#228]
As main.py has got a [high churn](https://codeclimate.com/github/raiden-network/scenario-player/trends/churn) and [no coverage](https://codecov.io/gh/raiden-network/scenario-player/src/master/scenario_player/main.py) tests should be added.

----------------------------------------------------------------------

`scenario_player.main.construct_log_file_name`
======================================
- [ ] The log file name contains the time of command invocation as a timestamp.
- [ ] The log file name contains the cli command.

- If a scenario file is given:

    - [ ] The log file name additionally contains the scenario name.
    - [ ] The log file is created in `${DATA_PATH}/scenarios/${SCENARIO_NAME}`.

- if a scenario file is not given:

    - [ ] The log file is created in `${DATA_PATH}/scenarios/`.

`scenario_player.main.configure_logging_for_subcommand`
================================================
- [ ] The log file's path is created if it does not exist.
- [ ] Sub command logging is setup using `raiden.log_config.configure_logging`.

    The function is called with the following expected values:

    - [ ] The `raiden` logger's log level is set to `DEBUG`.
    - [ ] The `scenario_player` logger's log level is set to `DEBUG`.
    - [ ] The global logger's log level is set to `INFO`.
    - [ ] The `scenario_player` is registered as a first-party packages with the raiden logger.
    - [ ] The debug log file level filter for the `scenario_player` is set to `DEBUG`.

`scenario_player.main.run`
=====================

`scenario-file` Positional Argument
-----------------------------------
- [ ] The CLI positional command `scenario-file` is required for the `run` command.

    - [ ] Its value must be an existing yaml file.
    - [ ] The file's content must be valid yaml.
    - [ ] If any of above are not True, the input is rejected.

`--chain` Flag
--------------
- [ ] The CLI flag `--chain` is required for the `run` command.

    - [ ] Its value is expected to fit the pattern `<chain_name>:<chain_netloc>`; it is rejected otherwise.
    - [ ] The flag may be passed multiple times.

- [ ] The CLI flag `--auth` is optional for the `run` command.

    - its value is expected to fit the pattern `<username>:<password>`; it is rejected otherwise.

`--keystore-file` Flag
----------------------
- [ ] The CLI flag `--keystore-file` is required for the `run` command.

    - [ ] The value of the parameter is a path to an existing file.

`--passoword` Flag
------------------
- [ ] The CLI flag `--password` is required for the `run` command.

    - [ ] Its value is either a file path, a string or pipe'd from stdin.
    - [ ] Its value is used to unlock the keystore file:

        - [ ] If it's a string, it's used as is.
        - [ ] If it's a file or stream, its contents are read and used in the unlock process.

    - [ ] If the password is invalid, an exception is raised.

`--notfify-tasks` Flag
----------------------
- [ ] The CLI flag `--notify-tasks` is optional for the `run` command.

    - [ ] It supports the value `rocket-chat`.
    - [ ] The value `rocket-chat` requires the ENV variable `RC_WEBHOOK_URL` to be set.

`--mailgun-api-key` Flag
------------------------
- [ ] The CLI flag `--mailgun-api-key` is optional for the `run` command.

    - [ ] It defaults to a falsy value, if not given.

- [ ] The func `send_notification_mail` is executed, if `--mailgun-api-key` is truthy, even when exceptions are raised during `ScenarioRunner.run_scenario`.

    - [ ] `ScenarioAssertError` sends result "Assertion Mismatch in <scenario file name>", with the assertion error.
    - [ ] `ScenarioError` sends result "Invalid Scenario <scenario file name>" with the traceback.
    - [ ] On any other exception it sends "Error running scenario <scenario file name>" with the traceback.
    - [ ] On no exception it sends result "Scenario successful <scenario file name>".

 Runner Setup
 ------------
- [ ] Tasks are collected using `scenario_player.utils.collect_tasks` before initializing the scenario runner.
- [ ] The SPaaS stack is started before initializing the scenario runner.
- [ ] The runner's `__init__` is called with the following parameters:

    - [ ] The loaded and unlocked account object.
    - [ ] A name-to-url mapping of test networks.
    - [ ] The value of the `--auth` flag.
    - [ ] The value of the `--data-path` flag.
    - [ ] The value of the `scenario-file` cli option.

Runner execution
----------------
- [ ] The method `scenario_player.runner.ScenarioRunner.run_scenario` is called after setup is complete.

    Before the method is called:

    - [ ] CLI arg parsing is completed
    - [ ] Setting up loggers is completed
    - [ ] Starting the SPaaS stack is done
    - [ ] Initializing the Runner is done

    Upon the method's completion:

    - [ ] The SPaaS stack is torn down.
    - [ ] The Node Controller's `stop()` method is called.
    - [ ] The UI greenlets are joined, or killed (if unresponsive).

**Comment by nlsdfnbch** [comment]
Added a first round of needed test cases.
