### ISSUE TITLE
CircleCI Fails on `prep-system` step.

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#230]
Description
=========
All workflows fail on the `prep-system` step, during the installation of the project:

Sample Stacktrace:
```
Collecting matrix-synapse==0.33.9 (from -r https://raw.githubusercontent.com/raiden-network/raiden/develop/requirements/requirements-dev.txt (line 86))
  Downloading https://files.pythonhosted.org/packages/ce/ea/694d662d627a77e322bfaa1e30773766778dc28edffd4c10a34fbfa737c7/matrix-synapse-0.33.9.tar.gz (1.0MB)

    100% |████████████████████████████████| 1.0MB 28.6MB/s 
  Installing build dependencies ... - \ | done
  Getting requirements to build wheel ... - error
  Complete output from command /home/circleci/ci/venv/bin/python /home/circleci/ci/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplovprxil:
  Traceback (most recent call last):
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 220, in assert_string_list
      assert isinstance(value, (list, tuple))
  AssertionError
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/circleci/ci/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/circleci/ci/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/circleci/ci/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 146, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 98, in <module>
      cmdclass={'test': TestCommand},
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 144, in setup
      _install_setup_requires(attrs)
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 133, in _install_setup_requires
      (k, v) for k, v in attrs.items()
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 446, in __init__
      k: v for k, v in attrs.items()
    File "/usr/local/lib/python3.7/distutils/dist.py", line 292, in __init__
      self.finalize_options()
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 734, in finalize_options
      ep.load()(self, ep.name, value)
    File "/tmp/pip-build-env-b79u3mr6/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 225, in assert_string_list
      "%r must be a list of strings (got %r)" % (attr, value)
  distutils.errors.DistutilsSetupError: 'dependency_links' must be a list of strings (got dict_values([]))
  
  ----------------------------------------
Command "/home/circleci/ci/venv/bin/python /home/circleci/ci/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplovprxil" failed with error code 1 in /tmp/pip-install-vh8_dv3p/matrix-synapse
You are using pip version 19.0.3, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Makefile:23: recipe for target 'install-dev' failed
make: *** [install-dev] Error 1
Exited with code 2
```

Example failing workflow:
https://circleci.com/gh/raiden-network/scenario-player/1504

Expected Behavior
===============
The installation should succeed and the workflow continue.

Steps to reproduce
===============
1. ssh into CircleCI machine (using `rerun step with ssh` option on the CircleCI app)
2. cd to `~/ci/scenario-player`
3. run `~ci/venv/bin/pip install -r https://raw.githubusercontent.com/raiden-network/raiden/develop/requirements/requirements-dev.txt`
4. Observe failure in `matrix-synapse` installation.

**Comment by nlsdfnbch** [comment]
Not reproducible locally, but reliably fails on every workflow on CircleCI.

**Comment by nlsdfnbch** [comment]
Between last success and first failure, no requirements were changed in `raiden`, nor `scenario-player.`

**Comment by nlsdfnbch** [comment]
Confirmed that neither `pip`, not `pip-tools` nor `setuptools` are the issue - ran identical versions on CircleCI via SSH of all packages which succeeded locally. The error persisted.

**Comment by Dominik1999** [comment]
> Between last success and first failure, no requirements were changed in `raiden`, nor `scenario-player.`

we changed to geth 1.9.2. yesterday. But the error doesn't seem to be related

**Comment by nlsdfnbch** [comment]
Confirmed that `matrix-synapse` has seen no changes neither `setup.py` nor `synapse/python_dependencies.py` files, hinting add an issue unrelated directly `matrix-synapse`.

**Comment by LefterisJP** [comment]
I will have a look as to how this may happen due to Raiden. Can't say much for SP itself.

**Comment by LefterisJP** [comment]
Hmmm this is probably the wrong issue for me. This seems to be related to SP installation.

**Comment by nlsdfnbch** [comment]
@ulope found a way to reproduce the issue locally:
```
docker run --rm -it -v /path/to/sp-checkout:/sp python:3.7 /bin/bash -c 'cd sp; make install-dev'
```

**Comment by ulope** [comment]
Looks like using `setuptools<41` avoids the problem.

**Comment by nlsdfnbch** [comment]
Emphasis on **avoids** - however, running setuptools `41.1.0` locally on my machine  does not raise this issue in the venv.

**Comment by nlsdfnbch** [comment]
Also, it doesn't (on CircleCI at least) - using `setuptools=40.8.0`
https://circleci.com/gh/raiden-network/scenario-player/1508?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by luehrsFred** [comment]
I tried to install raiden manually on the CircleCI machine via SSH.

I noticed two different results: 

### Running Raiden CI Config manually

- I cloned a fresh raiden repo
- I followed the steps `creating virtual env` and `installing dependencies`
```
      - run:
          name: Installing dependencies
          command: |
            . ${VENV_PATH}/bin/activate
            pip config set global.progress_bar off
            pip install -U 'pip<19.0.0' wheel pip-tools
            pushd requirements
            pip-sync requirements-ci.txt _raiden-dev.txt
            popd
```

**This resulted in the same error as seen above**


However cloning a fresh raiden repo and installing dependencies with the make script `make install-dev` worked fine

- `pip install --upgrade pip setuptools pip-tools`
- `make install-dev`
```
install-dev: check-pip-tools clean-pyc force-pip-version
	touch requirements/requirements-local.txt
	cd requirements; pip-sync requirements-dev.txt _raiden-dev.txt
	pip install -c requirements/requirements-dev.txt -r requirements/requirements-local.txt
```

**Resulted in No Errors**

Maybe this helps

**Comment by luehrsFred** [comment]
> Also, it doesn't (on CircleCI at least) - using `setuptools=40.8.0`
> https://circleci.com/gh/raiden-network/scenario-player/1508?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I was using 
```
Name: setuptools
Version: 41.1.0
```

**Comment by nlsdfnbch** [comment]
Found a way to completely avoid this ridiculous error: we no longer install the `dev` dependencies of the `raiden` project, as we only really need one library from that.

The issue is, afterall, somehow related to `setuptools`, as this was released the night after the last success. What it's bloody problem is, we may never know. 

Workflows are expected to be back to green with #223 .

**Comment by nlsdfnbch** [comment]
Workflows back to green.

**Comment by ara4n** [comment]
The root cause of this (which just bit me too is):
 * You're using an ancient synapse - 0.33.9 is from last November, and there have been *all* the security and performance fixes in the world since then, particularly since synapse exited beta in June.
 * It seems setuptools started choking on the old `setup.py` file when executed under python3 at some point.  This was properly fixed back in Dec in https://github.com/matrix-org/synapse/commit/c26f49a6645a84730811ea7bc5158d826bc43484
 * A workaround for now would be:
```diff
diff --git a/setup.py b/setup.py
index 00b69c43f..051857f01 100755
--- a/setup.py
+++ b/setup.py
@@ -90,7 +90,7 @@ setup(
     packages=find_packages(exclude=["tests", "tests.*"]),
     description="Reference homeserver for the Matrix decentralised comms protocol",
     install_requires=dependencies['requirements'](include_conditional=True).keys(),
-    dependency_links=dependencies["DEPENDENCY_LINKS"].values(),
+    dependency_links=list(dependencies["DEPENDENCY_LINKS"].values()),
     include_package_data=True,
     zip_safe=False,
     long_description=long_description,
```
...but you really should upgrade Synapse.

**Comment by christianbrb** [comment]
@ara4n Thanks a lot :-) 

Reopening the issue to manage the follow up

**Comment by ulope** [comment]
@ara4n Thanks for reaching out.

We're aware that that's an ancient version. We're currently working on switching our transport layer to the matrix-nio library (raiden-network/raiden#4292) and in concert with that we'll also upgrade to a recent synapse version.

@christianbrb There's no need to keep this issue open here. We no longer use the raiden dev dependencies (since they're not needed) in the SP.

**Comment by ara4n** [comment]
very cool to use matrix-nio - it should work much much better than the old python SDK, and of course will give you E2E for free too.
