### ISSUE TITLE
Token network for token 0xABCd does not exist

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/scenario-player#247]
Description
=========
Running the scenario player on dev commit with PFS7 like scenario. 
```
(raiden_env) [krishna@krishna-pc scenario-player]$ git log
commit ef83e4b8b394a9f9bc1d122a589d46d4c2cec618 (HEAD -> dev, upstream/dev)
Merge: 2efb2f3 8ef2711
Author: Nils Diefenbach <nlsdfnbch.foss@kolabnow.com>
Date:   Mon Aug 19 10:04:55 2019 +0200

    [FIX-#242] Skip CI instead of fail on invalid commit message.
    
    Refactor commit message validation

```
gives the error below.
https://gist.github.com/agatsoh/47e1046f451634b5aa3951cf45742154

`Token network for token 0x12ed6dbCfA8603005eCa5Fcf17d39b13695C8087 does not exist`
May be related to #132

Expected Behavior
===============
The nodes should be able to find the token network related to the token because it registered the token network before.

**Comment by christianbrb** [comment]
Expired
