### ISSUE TITLE
Separate logging to one file per scenario

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#269]
Analysis
=======
Current State
-----------------
When the scenario player starts a run, it writes all logs to one file rather than create separate files. This used to be different.

Problem
-----------
It is difficult to get a good overview of what went wrong in a scenario when all scenarios are mixed together in the same log file at the moment. 

Solution
----------
The above problem would be solved if each scenario has it's own log file per run as it used to be in the past.

**Comment by christianbrb** [comment]
This might have been introduced by removing

https://github.com/raiden-network/scenario-player/blame/ee421cd16f0f7cf59073de94c6eba05e9f5b739d/scenario_player/main.py#L328-L352
