### ISSUE TITLE
Switch Nightly to Raiden Release Candidate once released

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#286]
Once the next Raiden Release Candidate (RC) has been released
- [ ] Switch scenario player to use RC
- [ ] Restart scenario player runs, when switch has been done
- [ ] Let the scenarios run nighly with RC
- [ ] Restart once during the day to have an additional run

**Comment by Dominik1999** [comment]
https://github.com/raiden-network/raiden/releases/tag/v0.200.0-rc1

This would be the RC gentlemen. Can you reset the scenario player accordingly?
