### ISSUE TITLE
Use block timeouts instead of seconds

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#29]
Currently the scenarios are using seconds for timeouts or wait time. This should be updated to use blocks instead, since this will remove flakiness of slow blocktimes etc.

**Comment by nlsdfnbch** [comment]
Issue moved to [raiden-network/raiden #4418](https://github.com/raiden-network/raiden/issues/4418) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nlsdfnbch** [comment]
The zenhub button was more obviously accessible, though :shrug:
