### ISSUE TITLE
Show scenario name when successful in #monitoring

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#308]
Analysis
=======
Current State
-----------------
Currently, when a scenario was successful the bot in RC only posts "Succesfully ran scenario!". 

Problem
-----------
Above makes it a bit difficult to identify which scenario that was successful since we run several scenarios at the same time now.

Solution
----------
Add the scenario name that was successful to the string that is posted in the monitoring logs.

And also: It's `successfully` not `succesfully` ;)

**Comment by nlsdfnbch** [comment]
Also took care of the IP/url issue. Was less work than I thought. Still a hack though, but whatever.
