### ISSUE TITLE
scenario_player.exceptions.legacy.RESTAPIStatusMismatchError in PFS5 scenario

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/scenario-player#318]
Description
=========
The SP cannot find the token network contract related to the new token it deploys which is not required because we already mention the token to be used here
```
token:
  address: "0x62083c80353Df771426D209eF578619EE68D5C7A"
```
The token creation can be verified with this 
https://goerli.etherscan.io/address/0xb792dcfd1e4826838fe66b0b5e79b71b65f7a03f

The short trace of the error
```
f'HTTP status code "{resp.status_code}" while fetching {url}. '
scenario_player.exceptions.legacy.RESTAPIStatusMismatchError: HTTP status code "409" while fetching http://127.0.0.1:60123/api/v1/channels. Expected 2..: {"errors": "Token network for token 0xB792DCfD1E4826838FE66b0b5E79B71B65F7A03F does not exist"}

```

[pfs5_too_low_capacity.zip](https://github.com/raiden-network/scenario-player/files/3604714/pfs5_too_low_capacity.zip)

Expected Behavior
===============
The scenario player must find the token network related to token `0x62083c80353Df771426D209eF578619EE68D5C7A` instead of deploying a new token each time.

**Comment by Dominik1999** [comment]
Same as #324
