### ISSUE TITLE
Token.init() must support explicit token address

### ISSUE THREAD

**Issue by ulope** [raiden-network/scenario-player#319]
Description
=========
The scenario definition can contain an explicit token address, e.g.:
```yaml
token:
  address: 0x2222222222222222222222222222222222222222
```

This was supported in the previous `get_or_deploy_token()` function https://github.com/raiden-network/scenario-player/blob/2946d479676325a7902ad9e1714af4cbdf0e5886/scenario_player/utils/legacy.py#L230-L252

But was lost in the transition to the `Token` class. Its `.init()` method only knows about new or reused tokens:
https://github.com/raiden-network/scenario-player/blob/078a0c92c00a67be0ada4fb4e35dfdd407c3e178/scenario_player/utils/token.py#L251-L255

Expected Behavior
===============
Support explicitly given token addresses.

**Comment by Dominik1999** [comment]
closed by #330
