### ISSUE TITLE
AssertPFSHistory should match routes independent of position

### ISSUE THREAD

**Issue by ulope** [raiden-network/scenario-player#321]
Analysis
=======
Current State
-----------------
The `AssertPFSHistory` task matches routes pairwise in order they are encountered.
This can be fragile esp. in combination with the new `distinct_routes_only` option since that can unpredictable change the order.

Problem
-----------
Routes are matched based on order.

Solution
----------
The routes need to be matched based on content instead.
- Matching routes are removed from a list
- If at the end no entries remain matching was successful
- If entries remain or not all expected routes could be matched, matching was a failure

**Comment by Dominik1999** [comment]
closed by #328
