### ISSUE TITLE
AssertPFSHistory option expected_fees needs documentation

### ISSUE THREAD

**Issue by ulope** [raiden-network/scenario-player#323]
Description
=========
The `AssertPFSHistory` task option `expected_fees` is not documented.

Expected Behavior
===============
The `AssertPFSHistory` task option `expected_fees` is documented.

**Comment by christianbrb** [comment]
@ulope Do you know who could document that?

**Comment by czepluch** [comment]
Done with https://github.com/raiden-network/scenario-player/pull/380
