### ISSUE TITLE
Fix PytestUnknownMarkWarnings

### ISSUE THREAD

**Issue by ulope** [raiden-network/scenario-player#325]
Description
=========
The test suite uses some pytest marks without defining them. This leads to warnings:
- `PytestUnknownMarkWarning: Unknown pytest.mark.token_network_discovery`
- `PytestUnknownMarkWarning: Unknown pytest.mark.depends`

Expected Behavior
===============
No warnings to appear.
The error message points to https://docs.pytest.org/en/latest/mark.html for docs how to register the marks.

**Comment by christianbrb** [comment]
Should be done anyway, when touching the code
