### ISSUE TITLE
Do all scenarios use the same token?

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#332]
Description
=========
Since 12.09. [all scenarios](https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios) should use the same token as defined in 

``` 
token:
  address: "0x62083c80353Df771426D209eF578619EE68D5C7A"
``` 
but the Raiden Explorer shows only 6 disjoint figures / graphs with 13 scenarios 
https://goerli.explorer.raiden.network/tokens/0x62083c80353Df771426D209eF578619EE68D5C7A

This cannot be. We need to see 13 new disjoint figures / graphs every night.

- So either not all scenarios use the same token
- Or the Raiden explorer page is buggy

So can you please check

- [ ] did all scenario nightly runs on the 13.09. use the same token as defined above?
- [ ] [Please define next step ...]

**Comment by nlsdfnbch** [comment]
https://github.com/raiden-network/scenario-player/pull/330 had not been merged, so the given token address was not honored - hence, the scenarios did not use the same token.
