### ISSUE TITLE
Error communicating with a desired service!

### ISSUE THREAD

**Issue by palango** [raiden-network/scenario-player#335]
Description
=========

The SP crashes while running a scenario.

Expected Behavior
===============
Shouldn't crash

 Logs:
[scenario-player-run_ms1_simple_monitoring_2019-09-18T12:42:17.log](https://github.com/raiden-network/scenario-player/files/3625949/scenario-player-run_ms1_simple_monitoring_2019-09-18T12.42.17.log)

**Comment by palango** [comment]
https://gist.github.com/palango/27de6fccecedafca282e2bcd4c56ab19

**Comment by nlsdfnbch** [comment]
It looks like the JSONRPCCLient in `raiden` is doing some invalid concatenation:
```
File \"/Users/paul/Projects/brainbot/scenario-player/scenario_player/services/rpc/blueprints/tokens.py\", line 111, in deploy_token
    constructor_parameters=(1, decimals, name, symbol),\n  File \"/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/raiden/network/rpc/client.py\", line 574, in deploy_single_contract\
   receipt = self.poll(transaction_hash)\n  File \"/Users/paul/Projects/brainbot/scenario-player/venv/lib/python3.7/site-packages/raiden/network/rpc/client.py\", line 663, in poll
    tx_receipt[\"blockNumber\"] + self.default_block_num_confirmations
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'"}
```

**Comment by palango** [comment]
After updating raiden this works now.
