### ISSUE TITLE
Not? using the JSONRPC-Client from the Raiden client to interact with the blockchain

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#342]
Analysis
=======
Current State
-----------------
Currently, the scenario player is using the JSONRPC-Client from the Raiden client to interact with the blockchain. For all other operations, it is using the Raiden API and CLI.

Problem
-----------
The JSONRPC-client is a "private" Raiden client feature.

This leads to several problems
- eg. https://github.com/raiden-network/scenario-player/issues/315
- Using "Wait" tasks for synchronization
- Maintainability, if Raiden client is getting refactored
- Seperation of concerns
- ... please extend ...

and makes it hard to debug and fix issues.

Solution
----------

- [ ] Analyse which features/tasks are using the JSONRPC-client
- [ ] Decide on next steps

**Comment by nlsdfnbch** [comment]
Generally speaking, any operation that requires sending a transaction, makes use of the JSONRPCClient class.

An issue I see, which is closely related to maintainabilty mentioned above, is that due to tight coupling of the SP with the raiden contracts, changes in those repositories are guaranteed to almost always result in errors/bugs in the SP.

**Comment by konradkonrad** [comment]
After a conversation with client devs, I believe the proper way is using the raiden client proxies: https://github.com/raiden-network/raiden/tree/develop/raiden/network/proxies

This also relates to #349 -- using the proxies, all transactions will be logged.

**Comment by konradkonrad** [comment]
See also https://github.com/raiden-network/scenario-player/issues/315

**Comment by palango** [comment]
Starting with https://github.com/raiden-network/scenario-player/pull/511 we will use the proxies Raiden uses.
