### ISSUE TITLE
Add to example yaml: Allow passing multiple values to Raiden CLI Option as list

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#344]
Analysis
=======
Current State
-----------------
The file https://github.com/raiden-network/scenario-player/blob/master/examples/scenario-example-v2.yaml contains the main documentation of how a scenario is getting configured.

With https://github.com/raiden-network/scenario-player/pull/337 we have introduced a way how allow passing multiple values to Raiden CLI Option as list.

Examples can be found here: https://github.com/raiden-network/raiden/pull/4967/files

Problem
-----------
The https://github.com/raiden-network/scenario-player/blob/master/examples/scenario-example-v2.yaml file does not contain this option yet.

Solution
----------
Add an example how to allow passing multiple values to Raiden CLI Option as list in the https://github.com/raiden-network/scenario-player/blob/master/examples/scenario-example-v2.yaml file

**Comment by nlsdfnbch** [comment]
done
