### ISSUE TITLE
Describe the usage of the option `max_funding` and how it interacts with `balance_min` in the example yaml file

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#345]
Analysis
=======
Current State
-----------------
Currently, the usage of the option `max_funding` and how it interacts with `balance_min` is not obvious.

Problem
-----------
If just `balance_min` is used the scenario might run into an error like `{\"errors\": \"Not enough balance to deposit. 0x62083c80353Df771426D209eF578619EE68D5C7A Available=50000 Needed=1000000000000000000\`

Solution
----------
Describe the usage of the option `max_funding` and how it interacts with `balance_min` in the [example yaml file]( https://github.com/raiden-network/scenario-player/blob/master/examples/scenario-example-v2.yaml).

**Comment by nlsdfnbch** [comment]
done
