### ISSUE TITLE
Move scenarios to be run during nightlies to correct folder

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#348]
In order to avoid further issues like #343 in the future, please ~append the suffix `.nightly` to the scenario names~ move all scenarios you'd like to run on the SP servers at night to the `ci` subfolder in the `raiden/raiden/tests/scenarios` directory.

Create folders per instance, named as follows:
- [ ] `sp1` 
- [ ] `sp2`

And move/copy the appropriate scenarios in these folders. The SP instances will each run all files ending in `.yaml` when triggering runs.

**Comment by ulope** [comment]
There is a directory called `ci` In the `scenarios` one which was originally intended for this purpose.

**Comment by nlsdfnbch** [comment]
well, that's even better then.

**Comment by christianbrb** [comment]
@nlsdfnbch Would that work if it is getting done now? If yes, I would move the issue to the Raiden repo

**Comment by nlsdfnbch** [comment]
It's required as of now.
The following folders are needed:

- raiden/raiden/testing/scenarios/ci/sp1
- raiden/raiden/testing/scenarios/ci/sp2

**Comment by nlsdfnbch** [comment]
scenarios moved with https://github.com/raiden-network/raiden/pull/5444
