### ISSUE TITLE
Delete dev and just use master

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#361]
## Problem
I am still having a hard time figuring out which issues are just closed, which ones are released and which ones are just in dev.

I was looking for the fix for #337 and couldn't it in https://github.com/raiden-network/scenario-player/blob/master/examples/scenario-example-v2.yaml

Then I have realized, that it might be still only in dev even though the option to use it is already in master and released.

## Proposed solution
- Delete the dev branch

CC @nlsdfnbch

**Comment by nlsdfnbch** [comment]
This was planned for the future anyway. However, I wanted to achieve some minimal test coverage of the setup components before moving ahead with this. I'd be fine with doing this after we have #350 done

**Comment by christianbrb** [comment]
Currently the nightlies are running on the dev branch

**Comment by nlsdfnbch** [comment]
#350 has been completed, and we can move forward with this issue.
