### ISSUE TITLE
Dockerize the scenario player

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#363]
Analysis
=======
Current State
-----------------
We currently pull the raiden and SP repo grom github via a bash script, build a docker container and use it in the nightlyies, every night.

Problem
-----------
The bash script is delicate and not exactly robust, the process of building a docker container is
additional load which can be easily offloaded to dockerhub.

Solution
----------
Write a new docker setup for the scenario player

**Comment by nlsdfnbch** [comment]
Does this concern the SP instance Docker setup, or the setup of the repository, @christianbrb ?

**Comment by christianbrb** [comment]
As far as I remember it was the SP instance docker setup you've been working on :)

**Comment by nlsdfnbch** [comment]
Dockerfile was updated and the bilds for `dev` work as expected.
