### ISSUE TITLE
Write a log configuration for raiden nodes to log to our EFK server

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#403]
Currently, logs are written to a file locally - in order to debug issues, they have to be downloaded. The downloading has been unreliable, as well as the node-packing error prone.

As of recent, we are running an EFK stack at `logs.raiden.network`, we can send these logs to it instead, ridding ourselves of the need to host log files via HTTP, making them more easily searchable via kibana/elastic and allowing us to do away with a bunch of (then) deprecated code concerning logs and their packing/serving.

Requirements:
- [ ] A sample logging configuration for the raiden nodes to run and send their logs to the log aggregator

- [ ] An option to log and send the sp log files to the log aggregator (possible as a logging handler)

**Comment by konradkonrad** [comment]
> ridding ourselves of the need to host log files via HTTP

I don't think we can get rid of this, because logging is only part of what is needed for debugging. We will still need to host WAL-DBs+respective logs, in order to allow a deeper look.

**Comment by nlsdfnbch** [comment]
Not sure I'm following you:
I'm talking about having to serve the log files that we're currently serving via http - those would not be necessary anymore if all our logs are available via kibana.

**Comment by nlsdfnbch** [comment]
In order to stay compatible with the debugging tool provided by @konradkonrad , we'll log to both kibana *and* a log file on the server.

**Comment by palango** [comment]
We won't use the EFK stack at logs.raiden.network short term.
