### ISSUE TITLE
I want to restart scenarios at the point of failure with the fix included 

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#419]
Analysis
=======
Current State
-----------------
Running a scenario takes a long time until I reach the point where I want to see if my fix worked or not (in the bf1 scenario (very good scenario btw @czepluch) it takes 15 minutes).

Problem
-----------
I want to see faster if my fix worked. 

Solution
----------
I want to restart a scenario at a certain point, the point of failure. If a scenario fails constantly at the transfer 73 I want to see the scenario failing. Then I want to fix something in the code and restart the scenario at transfer 73. 

----------------------------------------------------------------------
User Stories
==========
I as a developer want to restart a scenario at the point of failure after I fixed code in one of the corresponding modules.

... I know that sounds hard and there are many reasons why this doesn't work but it is a wish list :)

**Comment by nlsdfnbch** [comment]
That's a pretty big item for a wishlist :smile: but no worries, we'll see what can be done!
