### ISSUE TITLE
Scenario Player as integration test tool triggered with CircleCI

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#420]
Analysis
=======
Current State
-----------------
The scenario player is triggered every night. During a day, normally many different PRs get merged. This tool gets more and more important for us since it tests all our modules at once. 

Problem
-----------
So if a scenario fails, we have to pinpoint manually which PR has broken the scenarios. 

Solution
----------
It would help us if the scenario would start after every PR and we get a report like in CircleCI. Therefore, we need faster scenario runs which means more parallelization. 

----------------------------------------------------------------------
User Stories
==========
I want to see after every PR push and before the merge if it would break our scenarios. So all scenarios should runs like integration tests before I am able to merge my PR.

**Comment by nlsdfnbch** [comment]
related #201 and splitting out services as standalone containers
------------------------------------

First-thought-solutions:
- [ ] Trigger Scenarios Via HTTP (auth? VPN? BB nodes?)
- [ ] Introduce CircleCI Step to request scenario runs
- [ ] Concurrently run scenarios, requires stand-alone RPC service (code exists, must only be migrated; started migration in separate branch, needs to be uploaded tho)

**Comment by palango** [comment]
Currently the SP is to slow for that. I'm closing it now, but we can reopen if we improved the runtime.
