### ISSUE TITLE
Run scenarios at 22:00

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#436]
### Introduction
Currently the scenarios run at 02:00. This means that often not all scenarios have finished when people start working. 

### Solution
Start the scenarios at 22:00 instead of 02:00.

**Comment by nlsdfnbch** [comment]
This is possible as long as we do not test against nightly builds (which haven't been built by 22:00h).

**Comment by christianbrb** [comment]
Moving the bf scenarios to SP1 would be another option

**Comment by nlsdfnbch** [comment]
Set the nightlies to run at `22:00`, as opposed to `01:45`.
