### ISSUE TITLE
Stopping / Waiting on nodes fails with greenlet Exception

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#438]
Seems like this was fixed in https://github.com/raiden-network/scenario-player/pull/439 find out if this is the case and close issue. If not, fix underlying issue
+++++
Observed in #433 #434 #435

According to @czepluch , the raiden node has been slower to stop in the past week, which may be the source of the error.

The `wait` task does not appear to be an actual `TaskError` - the caught `GreenletExit` exception actually indicates that the Greenlet completed successfully.  [source](http://www.gevent.org/api/gevent.greenlet.html#gevent.GreenletExit)
@ulope should add his thoughts on this, as he's the original author.

**Comment by nlsdfnbch** [comment]
It appears this issue only happens during execution of these tasks in a `serial` task

**Comment by Dominik1999** [comment]
closing this, it seems to be fixed
