### ISSUE TITLE
SP Features - Kill list, wish list, external low-hanging fruits

### ISSUE THREAD

**Issue by deepbrook** [raiden-network/scenario-player#440]
As discussed in our meeting on the 12.05.2019, this issue will include the following three lists, as supplied by @Dominik1999 , @hackaugusto and myself:

- [x] List of wished-for features supplied by the SP (@Dominik1999 ) 
- [x] [List of low-hanging fruits](https://github.com/raiden-network/team/issues/694) in the `raiden` client which could improve scenario execution performance (@hackaugusto )
- [x] List of least-/unused features in the SP (@nlsdfnbch )

**Comment by nlsdfnbch** [comment]
Feature Kill llist
-------------------

- [ ] urwid-powered UI -> Accounts for roughly 500 lines of untested code.
- [ ] click-powered cli -> accounts for 250 lines of un-tested code; I'm biased, though - I believe `argparse` can do just what we need, as I do not see any of the features that may make `click` superior to it, used.
- [ ] `gevent` -> replacable with asyncio imo, which is less oddly behaving that gevent.

**Comment by nlsdfnbch** [comment]
Augusto's list https://github.com/raiden-network/team/issues/694

**Comment by Dominik1999** [comment]
Hey, thank you Nils!
At the moment, I just need
- bug Fix: https://github.com/raiden-network/scenario-player/issues/438 (Highly important, we can also try to help you there)
- logging in whichever way. I want to see when a scenario is green or when it fails. I / sohan can look the logs up when it fails for now

**Comment by Dominik1999** [comment]
ok what are the next steps here? Who is in charge?
@nlsdfnbch @hackaugusto @christianbrb

**Comment by nlsdfnbch** [comment]
@Dominik1999 At least from the SP perspective this can be paused until after the raiden release - all my changes are code changes, and my potentially introduce bugs.
