### ISSUE TITLE
Make scenario specific setting overwritable: PFS

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#442]
Analysis
=======
Introduction
-----------------
Currently each scenario has some hardcoded settings specified. Some of these settings should be made overwritable through the CLI arguments of the scenario player when starting a scenario in order to make scenarios more dynamic in regards to which environment they are run in. This should be done as a solution to https://github.com/raiden-network/team/issues/682. 

At the moment the PFS services are hardcoded per scenario. 

Solution
----------
Make it possible to overwrite the
```
    pfs:
      url: https://pfs-goerli-with-fee.services-dev.raiden.network
```
setting through an argument when starting the Scenario Player.

**Comment by nlsdfnbch** [comment]
This can be handled using a jinja2 template - no changes required.
