### ISSUE TITLE
Make scenario specific setting overwritable: Token address

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#443]
Analysis
=======
Introduction
-----------------
Currently each scenario has some hardcoded settings specified. Some of these settings should be made overwritable through the CLI arguments of the scenario player when starting a scenario in order to make scenarios more dynamic in regards to which environment they are run in. This should be done as a solution to https://github.com/raiden-network/team/issues/682. 

At the moment the address of the token used is hardcoded per scenario. In case we want to run the scenarios in different environments it will be convenient to be able to specify which token to use.

Solution
----------
Make it possible to overwrite the
```
token:
  address: "0xADDRESS"
```
setting through an argument when starting the Scenario Player.

**Comment by nlsdfnbch** [comment]
This can be handled using a jinja2 template - no changes required.
