### ISSUE TITLE
Make scenario specific setting overwritable: Matrix server

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#445]
Analysis
=======
Introduction
-----------------
Currently each scenario has some hardcoded settings specified. Some of these settings should be made overwritable through the CLI arguments of the scenario player when starting a scenario in order to make scenarios more dynamic in regards to which environment they are run in. This should be done as a solution to https://github.com/raiden-network/team/issues/682. 

At the moment the matrix server used per node can be defined in the scenario file. If no matrix server is specified Raiden will automatically choose the one with best round time, which is desired behavior for the user, but if we want to simulate that nodes are located far from each other it's convenient to be able to specify which matrix servers to use. @nlsdfnbch alternatively mentioned the option to physically spin up the Raiden nodes on different Digital Ocean servers around the world.

Solution
----------
Make it possible to overwrite the
```
  node_options:
    0:
      matrix-server: https://transport01.raiden.network
```
setting through an argument when starting the Scenario Player.

**Comment by nlsdfnbch** [comment]
This can be handled using a jinja2 template - no changes required.
