### ISSUE TITLE
Proper logging for node startup failures

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#450]
check https://github.com/raiden-network/raiden/issues/5459

**Comment by nlsdfnbch** [comment]
@Dominik1999 will inform me if/once exit codes are available (https://github.com/raiden-network/raiden/issues/5461)

Meanwhile, the following will be implemented:
- [ ] Node startup failures no longer cause silent errors
- [ ] If node fails to start, parse logs for reason and log an exception pointing it out

Once https://github.com/raiden-network/raiden/issues/5461 is done, the implementation will be altered as follows:
- [ ] Node startup failures raise an exception describing the startup issue using `raiden`'s exit code.

**Comment by christianbrb** [comment]
Related https://github.com/raiden-network/raiden/issues/5472

**Comment by christianbrb** [comment]
More comments (Meta-Issue) https://github.com/raiden-network/raiden/issues/5433

**Comment by nlsdfnbch** [comment]
As discussed in the daily, this is fixed.
