### ISSUE TITLE
Reenable monitoring feedback if scenario failed or succeded

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/scenario-player#452]
Analysis
=======
Current State
-----------------
No feedback to #monitoring

Problem
-----------
I have to log in to the server to see if it failed or not

Solution
----------
Reenable bash script on server to post result of scenario run to #monitoring

**Comment by nlsdfnbch** [comment]
Re-implemented the func calls to the RC webhook, posting failure/success of each scenario after its docker container ran.
Will check setup after transport resizing is done.

**Comment by nlsdfnbch** [comment]
Failures will now post the following message to #monitoring:

```
:sad_panda: [SP1] Scenario ${scenario_name} Failed
```
