### ISSUE TITLE
BF1 scenario fails after all task have passed successfully

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#458]
Description
=========
The entire scenario seems to run successfully, but in the very end the scenario fails with 
```
{"result": "scenario error", "event": "Run finished", "logger": "scenario_player.main", "level": "error", "timestamp": "2019-12-11 23:53:25.451551"}
```

I cannot tell if this is a scenario player error or an error when shutting down Raiden nodes.

Logs:
- [SP logs](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/scenario-player-run_bf1_basic_functionality_2019-12-11T22%3A02%3A51.log)
- [Node0](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_12_000/)
- [Node1](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_12_001/)
- [Node2](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_12_002/)
- [Node3](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_12_003/)
- [Node4](http://139.59.211.171:8000/scenario-player/scenarios/bf1_basic_functionality/node_12_004/)

Expected Behavior
===============
It is expected that if all scenario tasks are successful that the #monitoring channel in RC will not report it as failing and that there will be no error in the scenario logs.

**Comment by czepluch** [comment]
Potentially related: https://github.com/raiden-network/raiden/issues/5472

**Comment by ulope** [comment]
I drive-by fixed the logging in that place in #457. It now includes the exception message and traceback.

**Comment by czepluch** [comment]
Same thing happened to the BF2 scenario.

Logs:

- [Scenario log](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/scenario-player-run_bf2_long_running_2019-12-11T23%3A53%3A31.log)
- [Node0](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_000/)
- [Node1](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_001/)
- [Node2](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_002/)
- [Node3](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_003/)
- [Node4](http://139.59.211.171:8000/scenario-player/scenarios/bf2_long_running/node_9_004/)

**Comment by czepluch** [comment]
And BF6

Logs:
- [Scenario log](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/scenario-player-run_bf6_stress_hub_node_2019-12-11T23%3A45%3A01.log)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_000/)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_001/)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_002/)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_003/)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_004/)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_005/)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_006/)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_007/)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_008/)
- [node0](http://68.183.70.168:8000/scenario-player/scenarios/bf6_stress_hub_node/node_17_009/)

**Comment by czepluch** [comment]
We haven't seen this lately. I suggest we close the issue and reopen if we see it again, when the current matrix/performance fixes have been merged.
