### ISSUE TITLE
BF1, BF2 and BF4 fail since docker names were taken

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#460]
As already discussed with @nlsdfnbch in private we know the reason for these scenarios to fail. It was basically because there had been a scenario run in the afternoon where those 3 scenarios managed to start. The scenario run was stopped, but the docker names still existed when the nightly started and hence the scenarios failed immediately. 

Ideally this should not happen and we should be able to handle this more gracefully.

**Comment by nlsdfnbch** [comment]
This can be avoided in the future by extending the timestamp of the container names. Currently, the tag is generated as follows:
```bash
$(date +'%y-%m-%d')_${scenario_name}
```

Extending the format string of the `date` command should avoid the issue:
```bash
$(date +'%y-%m-%d_%H%-M-%S')_${scenario_name}
```

**Comment by czepluch** [comment]
I am not entirely sure if the suggested fix for this has been implemented yet. Handing it over to @nlsdfnbch to answer

**Comment by nlsdfnbch** [comment]
This is fixed.
