### ISSUE TITLE
[META] Get ScenarioPlayer codebase MyPy compliant

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#476]
Get the SP codebase MyPy compliant. It throws a lot of errors.

- [x] Enable MyPY checks in CI
- [ ] Pick an unannotated module, annotate it and whitelist it
- [ ] continue

timeboxed for 1 day for now

**Comment by karlb** [comment]
When https://github.com/raiden-network/scenario-player/pull/509 is merged, all errors are fixed and untyped defs are checked. Further todos are:

- Reconsider exclusion of service code (that code has been skipped until #502 is done)
- Enforce types by setting `disallow_untyped_defs = True`

I think we already have most of the benefit without those todos and can consider this done (when #509 is merged). The above limitations are visible in the `mypy.ini` and can be worked as part of other commits.
