### ISSUE TITLE
Reenable skipped tests

### ISSUE THREAD

**Issue by palango** [raiden-network/scenario-player#490]
- [ ] List here which tests are skipped and why, see [here](https://app.circleci.com/jobs/github/raiden-network/scenario-player/3633)
- [ ] Un-skip and fix it
- [ ] In case you cannot un-skip a certain list here and find someone to discuss to delete it

Work on it after #502 and #497 
Example: 
We need to reenable them:
- `TestNewTransactionEndpoint.test_new_transaction_calls_correct_rpc_client_function`
- `TestNewTransactionEndpoint.test_endpoint_requires_parameter_and_expects_types[None missing - correct types]`

**Comment by Dominik1999** [comment]
start after #495 is completed
