### ISSUE TITLE
Decide on improved SP process management

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#497]
Since we cannot cure the Sudden Node Death https://github.com/raiden-network/raiden/issues/5620 since Jan 10, we need to clear up the process management of the Scenario Player. 

- [x] Discuss design for process handling with @ulope (only 30 Minutes) and @hackaugusto at the beginning of sprint and document decision here.
- [x] Create follow up issue and close related issues (housekeeping)

- Konrad changed some process management in https://github.com/raiden-network/scenario-player/pull/498

- in #495 we decided against the microservice architecture, see #502 

+++
- maybe reuse Raiden Janitor #468 
- related, weird process handling #466
- related #465

**Comment by karlb** [comment]
https://github.com/raiden-network/scenario-player/issues/468 is the relevant follow up issue.
