### ISSUE TITLE
Limit the noise in the monitoring channel

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#53]
Now that we're through with initial debugging of the scenario player and the scenarios we should limit the amount of messages posted to the monitoring channel again. 

Suggestion is to only have a message for a started scenario and then either an error message with a link to the logs or a green light with link to logs.

**Comment by nlsdfnbch** [comment]
@ulope , have you already done this? The logs seem quieter than before. If so, I'll just close this.
