### ISSUE TITLE
Add back the example file for the scenarios

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#54]
The file showing examples of the different tasks and syntax was accidentally removed from the repo. This should be added back and be maintained when new tasks or syntax is added.

**Comment by nlsdfnbch** [comment]
As discussed with @ulope, a better approach would be to add docstrings to the related python classes, and render these using sphinx. This would both add back the example/documentation from that file, while also providing an easy-to-search reference listing.

Besides, we'll need proper docs anyway, so this is a more sensible approach imo. 
If ulo is not available for this during https://github.com/raiden-network/scenario-player/projects/2, I will simply migrate the information from the file to the docstrings instead, and open a separate issue for next quarter's iteration.

**Comment by ulope** [comment]
Yes having proper docs is definitely the way to go, but I don't think it hurts to resurrect the example file until the docs are here.
