### ISSUE TITLE
Implement snapshot feature for the Scenario Player

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/scenario-player#556]
## Reducing the time to debug
Debugging with the Scenario Player implies a lot of wasted time, i.e. setting up a new topology and deposits every time. The Scenario Player should allow getting back to an existing set-up when encountering an error. This feature will help us to debug faster.

## Finalize Ulo's WIP branch 
https://github.com/ulope/scenario-player/tree/feature/reuse_account_snapshot-support
Please make sure to write proper tests for this feature

**Comment by ulope** [comment]
The WIP branch is here: https://github.com/ulope/scenario-player/tree/feature/reuse_account_snapshot-support

**Comment by palango** [comment]
@ulope should share his state/knowledge on this while he's in Berlin.

**Comment by GataKamsky** [comment]
Person working on the issue should also consult @andrevmatos and see if the solution is compatible with LC.

**Comment by christianbrb** [comment]
We would like to also use the feature in the LC. Is this done or still WIP?

**Comment by palango** [comment]
Was implemented in https://github.com/raiden-network/scenario-player/pull/501
