### ISSUE TITLE
Flaky scenario runs: Not enough balance to deposit

### ISSUE THREAD

**Issue by palango** [raiden-network/scenario-player#574]
On the run of 6th of June we saw this error twice. This also happened before. The setup and funding of nodes seems to be flaky somehow.

```
Not enough balance to deposit. 0x59105441977ecD9d805A4f5b060E34676F50F806 Available=0 Needed=1000000000000000000
```

Scenario logs:
[Archive.zip](https://github.com/raiden-network/scenario-player/files/4745662/Archive.zip)

**Comment by GataKamsky** [comment]
Look into the Eth node logs as a starting point.

**Comment by palango** [comment]
The problem is that the `JSONRPCClient` in the scenario player does not have `block_num_confirmations` set, so the default of zero is used, which leads to the scenario being started when the block might not have arrived yet at the different clients, thus making it flaky.

This [transaction](https://goerli.etherscan.io/tx/0xcc0a593a16eae08e7c98df58b7631ea00607b31034582c186a6375ce23a2bbbc) was mined in block 
2879854, while the client tried to gas estimate in block 2879853
```
"approximate_block_number": 2879853, "node_gas_price": 1230000000, "event": "Transaction gas estimated",
```

The solution is to set `block_num_confirmations` to the default in Raiden.
