### ISSUE TITLE
Logging Service

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#59]
Analysis
=======

Current state
----------------
In order to successfully debug scenario assertion errors, the end-user will require logs from all components:

1. The Scenario Player
2. The raiden Nodes involved in the scenario run
3. The pathfinding service used, if any
4. The monitoring service used, if any

Problem
-----------
Acquisition and packing of these logs is currently a concerted effort of py/bash/kibana foo, which is error prone and partially un-versioned. In addition, the user experience is sub-par, as the locations for related files are on different servers/webservices

Solution
----------

Converge log creation/generation in a dedicated `service`.

Service Definition
==============

Domain
---------

The new service owns the following domain:

- Collecting logs from kibana (logs.raiden.network) for:
  - the `PFS`
  - the `MS`
  - the `spaas` services
  - the `raiden` Nodes
- Collecting WAL-DBs and Log files written to disk on the SP instance (for @konradkonrad's debugging tool at https://github.com/raiden-network/raiden/tree/develop/tools/debugging)
- Enable users to request a packed archive of all logs

Dependencies
------------------
Libraries:
- `structlog`

Services/Daemons:
- `fluentd` (log file scanning and forwarding to EFK stack)

issues:
- Store run number and associated files in a DB
- Forward logs from files to ES/Kibana via fluentd

Interface
-----------
OpenAPI Spec:
```yaml
path: /logs/{scenario}
  parameters:
      - name: scenario
        in: path
        required: true
        schema:
          type: string

      - name: run
        description: The list of run IDs to return logs for.
        in: query
        required: false
        schema:
          type: array
          items:
            type: int
          nullable: true
          default: null

      - name: date
        description: The start time of the search window to use when looking for logs. Defaults to earliest.
        in: query
        required: false
        schema:
          type: string
          format: date-time
          nullable: true
          default: null

      - name: level
        description: The log level to filter a logs message by. Logged messages with a lower log level will be discarded.
        in: query
        required: false
        schema:
          type: string
          default: debug

  get:
    description": >
      Return any logs matching the given filters.

    parameters:
     - name: raw
       description: If true, the logs will not be beautified using the json-to-html tool.
       in: query
       required: false
       schema:
         type: bool
         default: false

    - name: pack
      description: If true, this will return an archive containing all logs and db files for the given run. Please note that this may take a while, as logs will be downloaded from kibana. Subsequent requests will not trigger new packing, as the archive is cached automatically for 24h.
       in: query
       required: false
       schema:
         type: bool
         default: false

    responses:
      "200":
        content:
         application/json:
           schema:
             type: object
             properties:
               url:
                 type: string
                 format: url
            type: array
            items:
              type: object
              properties:
                service:
                  type: string
                  description: name of the object
                kibana:
                  type: url
                  description: URL to a KQL query to display the logs for the `service`.
                log_file:
                  type: url
                  description: File path to the log file for the related service on the SP instance (if applicable)
```

User Stories
==========
TBD

**Comment by nlsdfnbch** [comment]
@ulope , @palango , @karlb, @rakanalh 

Let me know your thoughts on the integration part. I would supply PRs for the respective projects after your approval.

**Comment by karlb** [comment]
Instead of adding a custom REST interface to retrieve logs, we could go with some standard tools to forward the logfiles as they are written. I'm not up to date on current choice of tools for this, but maybe one of the approaches listed on http://www.structlog.org/en/stable/logging-best-practices.html?

**Comment by rakanalh** [comment]
Not a fan of both solutions.
1. Push-based services means that we have some sort of a sentry / kibana log driver which we distribute along with Raiden or the services to push logs to a centralized server which could be concerning to users (though we would use it in development/debugging mode, but i think the very existence of it would be concerning)
2. Pull-based approach raises a question of security / privacy as the endpoints have to be protected / deactivated in non-development environments.

My alternative suggestion is to have Raiden & services log into JSON files and from there you can parse the files and push them to whatever the service is. Which i think you already do:

> Acquisition and packing of these logs is currently a concerted effort of py/bash foo, which is error prone and partially un-versioned.

Why is this more error-prone than what you're suggesting?

**Comment by nlsdfnbch** [comment]
> Why is this more error-prone than what you're suggesting?
Because it's partially in bash, and has been blowing up a few times before I got it to work. Using a service to handle this instead allows for better error handling and logging, than logfile redirects and pipe juggling.

>2. Pull-based approach raises a question of security / privacy as the endpoints have to be protected / deactivated in non-development environments.

Agreed (I added the same concerns in my issue after first posting it).

>Push-based services means that we have some sort of a sentry / kibana log driver

It does not. As stated in the issue, it's little to no effort to add a logging handler that sends the log statements to a configured server, to the `logging.Logger` object. In my mind, this is *deactivated by default*. I'll add that bit to the issue to clarify.


> Pull-based approach raises a question of security / privacy as the endpoints have to be protected / deactivated in non-development environments.

> Instead of adding a custom REST interface to retrieve logs, we could go with some standard tools to forward the logfiles 

As stated in the issue, that is my preferred approach. See previous address. 

> [..] to push logs to a centralized server which could be concerning to users [..]
Could you elaborate? You mentioned sentry, which is configurable, and whether or not you push to their hosted server or one of your own is up to the user, so I would argue your concern is unfounded.

**Comment by nlsdfnbch** [comment]
> My alternative suggestion is to have Raiden & services log into JSON files and from there you can parse the files and push them to whatever the service is. Which i think you already do

This approach requires me to maintain the following hard-coded targets:
- PFS url (scenario file)
- MS url (scenario file)
- Raiden log file location (SP code base)

If any of these change, logging will break. These changes are external, i.e. made in other projects, so as of now there's no guarantee these breaking changes will be found right away (because I guarantee updating these in the SP repo will be forgotten).

Having the components register with the logging service makes it easier to maintain and more fault-tolerant, imo.

**Comment by ulope** [comment]
I can definitely see that streaming logs in realtime is the preferred solution (it would for example make it possible to inspect the logs while a scenario is till running). 
However, I agree that it could possibly give the wrong impression if we were to distribute some bundled remote logging feature in the client.
But, it should be pretty simple to make the logging configuration flexible enough to allow arbitrary loggers to be added via the config file, which would probably be enough for our needs here.

The same could apply to the services esp. in combination with #44 which would give us much more control over how they are being run.

As for shipping both json and plain text logs, that shouldn't be necessary. We have the [json-log-to-html.py](https://github.com/raiden-network/raiden/blob/023cbf2c182e37dc392a60df6290c8959cccdaf2/tools/debugging/json-log-to-html.py) utility which will generate nicely human readable logs from the json format (and has additional features that could be re-used in the SP).

**Comment by nlsdfnbch** [comment]
>However, I agree that it could possibly give the wrong impression if we were to distribute some bundled remote logging feature in the client.

I simply fail to see this. The code is open source, the feature deactivated by default. Anyone can audit this code. Sure - it **could** log all your precious debug info to the NSA; But it would do so because you're configured it that way, no?

By that logic, If you're worried about features being abused for evil, we might just as well scratch the SP, as this could be used to test and develop attacks against the raiden network. :thinking:

**Comment by LefterisJP** [comment]
>However, I agree that it could possibly give the wrong impression if we were to distribute some bundled remote logging feature in the client

> I simply fail to see this. The code is open source, the feature deactivated by default. Anyone can audit this code. Sure - it could log all your precious debug info to the NSA; But it would do so because you've configured it that way, no?

I agree with Niels here, code is open, logging is configurable and off by default in production. I just don't see a problem.

**Comment by nlsdfnbch** [comment]
I have updated the epic to be more specific of what the service should offer. The streaming of logs to the service from other components will, for now, be pushed back.

**Comment by nlsdfnbch** [comment]
@ulope , @palango - am I correct that we agreed on using logstash? Or is this still being discussed? As stated on RC, as long as whatever we're using has a stable interface, I'm down with that. But piping/grepping logs from a docker container is simply not feasible.

**Comment by nlsdfnbch** [comment]
Updated the epic to accomodate recent changes/intended changes.

**Comment by palango** [comment]
Closing. See https://github.com/raiden-network/scenario-player/issues/495
