### ISSUE TITLE
raiden_version: support --raiden-version cli param and/or raiden_version environment to overwrite scenario's raiden_version

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/scenario-player#593]
Analysis
=======
Right now, if one wants to test Raiden with a different version/binary/executable, one needs to change the scenario file and set the `raiden_version` directly there. It'd be great to have it overwritten by a `--raiden-version` command line option and/or a `raiden_version` environment entry in the environment file, in order to easily test with a custom raiden version without the need to change the scenario itself.
This is needed in order to run the Raiden scenarios with the Light Client.

**Comment by christianbrb** [comment]
@ulope @Dominik1999 Any remarks or could we go ahead and implement this?
