### ISSUE TITLE
Scenario Player requires raiden, but it doesn't get installed when installing dependencies

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/scenario-player#594]
Description
=========
After installing the Scenario Player in a clean virtual env, trying to run it will give an error because `raiden` isn't installed in the same virtualenv. Detected while setting up SP to run with LightClient, which doesn't depend on `raiden` python package on itself.

Expected Behavior
===============
If `raiden` is a dependency, it should be pulled in while installing the Scenario Player.

**Comment by palango** [comment]
It's in the requirements though. Why would that not install `raiden` when installing the SP?
https://github.com/raiden-network/scenario-player/blob/50ce490e95c9a6bcf2766c013d31ccd962861ac5/pyproject.toml#L27

**Comment by palango** [comment]
@andrevmatos Do you mean that the scenario player itself doesn't start (because of missing dependencies), or that the scenarios do not run because the `raiden` executable is not installed?

**Comment by andrevmatos** [comment]
I confess I can't remember exactly, just created this issue because, upon creating a clean `venv` and installing SP on it (using `pip`, probably from the cloned git repo), and trying to run a scenario on it, it errored saying `raiden` wasn't installed, and only succeed after installing it manually. It may be required to check if this continues to be the case.

**Comment by palango** [comment]
This is kind of the same error as in https://github.com/raiden-network/scenario-player/issues/608

I created https://github.com/raiden-network/scenario-player/issues/610 to improve this but for now the easiest fix is to install the raiden develop.

```sh
cd ../raiden
make install-dev
cd ../scenario-player
make install-dev
