### ISSUE TITLE
Support downloading Raiden from CircleCI artifacts or arbitrary URLs, and relax package content constraint

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/scenario-player#595]
Analysis
=======
Currently, the `RaidenReleaseKeeper` supports downloading Raiden binaries only from hardcoded URLs. It'd be great to allow it to download from arbitrary URLs, specially if possible to include `circle_token` params for it to download from build artifacts.
Also, the current code hardcodes the package must contain a single file inside. That's hard to do with the LightClient, which requires (for now) distributing the `wrtc.node` WebRTC native NodeJS module as a separate file side-by-side with the `.js` bundled script. Also, for now, a `.sh` executable script is needed in order to call `node` system binary on such script, so these are at least 3 files needed in the package.
Maybe we could assert that there's only one executable in the package's root directory, and assume this is the entrypoint?
Related: #593

Problem
-----------
We would like the ReleaseKeeper to be able to download and keep LC packages as Raiden versions

Solution
----------
Support arbitrary URLs as Raiden versions, possibly with custom params from environment (for tokens), and relax package content contraint, which currently requires the package to contain exactly one file.

----------------------------------------------------------------------
User Stories
==========
User can set a URL as Raiden version, and environment variables for possible additional params for the URL or headers (for CircleCI artifact access). This package may contain more than one file or even folders, but it's reasonable to assume exactly one executable file on the root, which is to be used as raiden's entrypoint. Different versions may be kept on different folders and not conflict with each other (maybe by URL's hash, or something like that). This version is to be used to run the SP.

**Comment by christianbrb** [comment]
@ulope @Dominik1999 Any remarks or could we go ahead and implement this?

**Comment by palango** [comment]
In #603 I removed the `ReleaseKeeper` as defining the version to use in the scenario looks like the wrong path (and would lead to lots of duplicated scenarios)

Instead the executable to use can be chosen now and the setup should be done before running the scenario player.

For the light client, this would mean adapting the script here: https://github.com/raiden-network/light-client/blob/master/serve_pr/ci_dapp.sh
And running it on the CI server

**Comment by palango** [comment]
In #603 the release keeper was removed. The download of the bundle should be done on the nightly run. (For the LC see https://github.com/raiden-network/light-client/issues/1977)
