### ISSUE TITLE
RPC Service - Running services concurrently

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#62]
Analysis
=======
Current state
----------------
The scenario player runs scenarios one at a time, increasing the overall run-time with each added scenario. Running them concurrently is not an option, due to `nonce` errors.

Problem
-----------
Running scenarios concurrently is not possible with the current SP version is not possible, due to errors in `nonce` generation: `raiden` expects complete and sole control over an account. Since several scenarios start several `raiden` instances, this assumption does not hold, and duplicate nonces are generated, causing our scenarios to error.

Solution
----------
Replace the use of `JSONRPCClient` in the `ScenarioRunner` with a micro service which manages RPC client instances for all currently running scenarios.

It must, essentially, take over all duties that include a `JSONRPCClient.send_transaction()` call.

Service Definition
==============

Domain
----------
The new service owns the following domain:

- Sending a transaction
- Deploy a token contract
- Mint tokens for a token contract 
- Update the allowance for a User Deposit Contract

Dependencies
------------------
Requires the following packages, in order to run correctly:

- `raiden`
- `raiden_contracts`
- `web3`
- `ethutils`

Requires no additional `SPaaS` services to run.

Interface
-----------

The following endpoints are exposed:

- `/rpc/client`
  - `POST` - creates a new `JSONRPCClient` instance, with a given configuration.
  - `DELETE` - removes an existing rpc instance from the client registry.
- `/rpc/contract`
  - `POST` - deploys a new token contract.
- `/rpc/contract/mint`
  - `POST` mints new tokens for a given address.
- `/rpc/tcontract/allowance`
  - `POST`  - updates the allowance for the given UDC contract.

Tasks
=======
- [ ] Testing

**Comment by palango** [comment]
Closing. See https://github.com/raiden-network/scenario-player/issues/495
