### ISSUE TITLE
Nodes got same port assigned

### ISSUE THREAD

**Issue by palango** [raiden-network/scenario-player#639]
Description
=========

In tonight's LC BF6 run node 3 and 7 got port `53771` assigned:

```
{"node": 3, "address": "0x6ebf9FC71796e9Fe1D4D3F3f2e6F1A72E08eD248", "port": "53771", "event": "Starting node", "logger": "scenario_player.node_support", "level": "info", "timestamp": "2020-11-17 01:21:27.660391"}
...
{"node": 7, "address": "0xf52e13611563d071E0b3f671364210A98FA73062", "port": "53771", "event": "Starting node", "logger": "scenario_player.node_support", "level": "info", "timestamp": "2020-11-17 01:21:27.764930"}

```

Expected Behavior
===============
Each node should get a unique port.

**Comment by palango** [comment]
@ulope Is this a race condition?

If so I'd retry as long a s there are duplicates in the list of nodes!?

**Comment by ulope** [comment]
Yes looks that way.

This is the function we use to get a free port number:

https://github.com/raiden-network/scenario-player/blob/a3665f4d8784cfb561fdeb908c198886f6ec3863/scenario_player/node_support.py#L235-L245

This has a race in so far as that a port that has not been connected to can immediately be reused by the kernel.

In the Raiden tests we used to have the same problem and solved it with this (which for some reason is only used on macOS at the moment):

https://github.com/raiden-network/raiden/blob/c1ab0e6ea6289c5853247700d066f1dcc9e1cf87/raiden/network/utils.py#L35-L71
