### ISSUE TITLE
Environment overwrites default options for `matrix_server` from scenario

### ISSUE THREAD

**Issue by ezdac** [raiden-network/scenario-player#664]
Description
=========
Our current test-drive of the scenarios of the presence-less branch in Raiden wants to use only `transport.transport05.raiden.network` as matrix_server for all nodes.
Therefore https://github.com/raiden-network/raiden/commit/42c8e4c5b07c574136265af5a16f5e14fb59c6e9 removed the individual transport assignment from the scenario's yaml files and provided a specific matrix_server as a default option.

In the scenario-player, this default option is silently overwritten, when a environment definition is present:
https://github.com/raiden-network/scenario-player/blob/d6937604987dea245999e1cb58c48fdf6ca7b9ea/scenario_player/definition.py#L47-L51

The environment always has a non-empty `matrix_servers` list:
https://github.com/raiden-network/scenario-player/blob/d6937604987dea245999e1cb58c48fdf6ca7b9ea/scenario_player/main.py#L263

And there is always an environment loaded for a run, due to a default fallback:
https://github.com/raiden-network/scenario-player/blob/d6937604987dea245999e1cb58c48fdf6ca7b9ea/scenario_player/main.py#L213

Expected Behavior
===============
The default option `matrix_server` should be overwriteable by the scenario files.
Therefore the value in the dict should only be set if it isn't present in the yaml file.
If it is necessary to verify the value of the matrix server's url, it could be checked wether the provided default is contained
in the environments' matrix_servers list.

**Comment by karlb** [comment]
>  self.nodes.dict["default_options"]["matrix-server"] = environment.matrix_servers[0] 

I think this line was not meant to overwrite the default, but to set a server when none was specified. We don't want transport server autodetection if transport servers are set in the env file.
