### ISSUE TITLE
SP2 failing all scenarios

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/scenario-player#675]
On May 19th, all scenario player runs at SP2 failed with the same/similiar message:
```
Traceback (most recent call last):
  File "/scenario-player/scenario_player/tasks/base.py", line 140, in __call__
    return_val = self._run(*args, **kwargs)
  File "/scenario-player/scenario_player/tasks/execution.py", line 36, in _run
    task()
  File "/scenario-player/scenario_player/tasks/base.py", line 140, in __call__
    return_val = self._run(*args, **kwargs)
  File "/scenario-player/scenario_player/tasks/execution.py", line 36, in _run
    task()
  File "/scenario-player/scenario_player/tasks/base.py", line 140, in __call__
    return_val = self._run(*args, **kwargs)
  File "/scenario-player/scenario_player/tasks/api_base.py", line 59, in _run
    f'HTTP status code "{resp.status_code}" while fetching {url}. '
scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code "402" while fetching http://127.0.0.1:39457/api/v1/channels. Expected 201: {"errors": "The account balance is below the estimated amount necessary to finish the lifecycles of all active channels. A balance of at least 1033700486102393600 wei is required."}
```

**Comment by konradkonrad** [comment]
The SP wallet on SP2 has [currently 80+ goerliETH](https://goerli.etherscan.io/address/0x8f5ea3bb3e99c317b8745918f6973f7afbf659c3)

**Comment by konradkonrad** [comment]
At the time of the error, the raiden client expected its account to have a balance of 
```
In [5]: Web3.fromWei(1033700486102393600, "ether")                                                                             
Out[5]: Decimal('1.0337004861023936')
```
around `1 ETH`. That is of course way above the `0.3 ETH` transferred at the beginning of the scenario.

The question remains: why would the raiden nodes on SP1 not throw the same error at the same time?

**Comment by konradkonrad** [comment]
That is the list of failed scenario containers:
```

**Comment by konradkonrad** [comment]
docker ps -a --no-trunc|grep -v "lc/raiden"|grep 20210519|cut -b571-
20210519T191945_pfs9_partial_withdraw
20210519T191733_pfs6_simple_path_rewards
20210519T191501_pfs3_multiple_paths
20210519T191232_pfs1_get_a_simple_path
20210519T191034_ms3_simple_monitoring
20210519T190835_ms2_simple_monitoring
20210519T190602_mfee4_combined_fees
20210519T190339_mfee1_flat_fee
20210519T185821_bf7_long_path
20210519T185418_bf6_stress_hub_node
20210519T185131_bf4_multi_payments_same_node
20210519T184907_bf3_multi_directional_payment
20210519T182947_bf2_long_running

**Comment by karlb** [comment]
This happens on both SP1 and SP2 now.

**Comment by karlb** [comment]
We are giving 0.3 ETH to each node, but the errors indicate that more ETH (1.03 in the case of the error in the top message) is needed.

**Comment by karlb** [comment]
[Goerli had frequent congestion issues recently.](https://gitter.im/goerli/testnet?at=60aceddd0ff6de262b2a35b8) With that in mind, theses errors might be reasonable, depending on the actual gas prices at the time. I can't find a data source for goerli gas prices, so this is still mostly speculation.

**Comment by istankovic** [comment]
@karlb, @konradkonrad is this issue still relevant?

**Comment by karlb** [comment]
This really was just the goerli network having problems.
