### ISSUE TITLE
Revert changes for high fixed gas prices

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/scenario-player#680]
Description
=========
During the `Bespin` release candidate testing, we switched the SP CI setups to use a fixed gas price setting of a rather high `500 gwei`. (See https://github.com/raiden-network/scenario-player/pull/679/files).
This, paired with an increased node funding, was meant to reduce failure noise that originated in weird gas price fluctuations in the `goerli` network.

Since this is neither a realistic test setup, nor a sustainable way to operate the scenario player (we'd run out of goerliETH quite soon), we need to roll back these changes and come up with more reasonable solutions (see also https://github.com/raiden-network/raiden/issues/7095).

The current change is activated through adjusting the variable
```diff
- SP_BRANCH=develop
+ SP_BRANCH=higher_funding
```
in `/var/lib/scenario-player/env.sh` on both SP CI servers.

~~Due to the related changes in https://github.com/raiden-network/raiden/pull/7087 and https://github.com/raiden-network/raiden/pull/7088 we may also have to adjust the [default environments in this repository](https://github.com/raiden-network/scenario-player/tree/master/scenario_player/environment).~~

**Comment by konradkonrad** [comment]
@ezdac please add anything I may have missed above!

**Comment by karlb** [comment]
> Due to the related changes in [raiden-network/raiden#7087](https://github.com/raiden-network/raiden/pull/7087) and [raiden-network/raiden#7088](https://github.com/raiden-network/raiden/pull/7088) we may also have to adjust the [default environments in this repository](https://github.com/raiden-network/scenario-player/tree/master/scenario_player/environment).

I fixed that with https://github.com/raiden-network/scenario-player/commit/d5e863e3191baabcb5782b6cb64568ae9204091f, already.
