### ISSUE TITLE
Automate Version upgrades

### ISSUE THREAD

**Issue by deepbrook** [raiden-network/scenario-player#91]
Add a periodic workflow to circleci upgrading dependencies, and running them against the current test harness.

Test only dependencies which `raiden` does not require.

Test each dependency sequentially, dropping any upgrades that would break the tests.

**Comment by christianbrb** [comment]
This is the right issue ;)

Within the light client project we looked into dependabot and renovate

Maybe @nephix or @kelsos could give an advice

**Comment by nephix** [comment]
Related light client issue: https://github.com/raiden-network/light-client/issues/345

So far we tried dependabot but it creates a new pull request for each dependency update, and rebases each PR on merge again, which triggers a lot of CI workflows each time.

So we're looking for a solution as well that batches dependency updates together

**Comment by nlsdfnbch** [comment]
You could certainly skip the CI on rebases, no? Separate PRs per dependency doesn't seem like a bad thing either. At least for us that seems like what we're looking for mostly. I'll have a look

**Comment by nephix** [comment]
Ideal for us would be (@kelsos please correct me if I'm wrong) a single pull request per week with all updated dependencies from that week. That pull request then triggers CI tests and we can quickly do manual tests to see if something broke even though tests succeeded. If everything went well, we simply merge the PR.

**Comment by nlsdfnbch** [comment]
Shouldnt your test harness cover the testing? Circle can run tests (even specific once for compatibility checks, if you so want) on PRs submitted by the bot, and all you need to check is if the checks passed. But alas, that's your decision to make, of course.

It's not a good idea to test all updates in one go (hence me favoring the per-dependency PR approach), since that can make debugging a pain in the ass. There also shouldn't be too many updates per-week (aside from probably the first time it runs).

**Comment by kelsos** [comment]
Nils for the light client the initial checks where too much but yes
afterward it should be easier, especially if you go with live updates.

Initially, I was thinking of batching to avoid spam on the CI but I can see
the merit on having a per-dependency approach. Also, the weekly schedule
makes less sense if you go on a per-dependency approach.

I am not sure if you can currently skip the ci on rebase, but there are
some issues in that regards open for dependabot.

**Comment by nephix** [comment]
> Circle can run tests (even specific once for compatibility checks, if you so want) on PRs submitted by the bot, and all you need to check is if the checks passed

> It's not a good idea to test all updates in one go (hence me favoring the per-dependency PR approach), since that can make debugging a pain in the ass

I guess CircleCI is pay-as-you-go and some of our tests are also quite heavy. So it's not only a technical question

> There also shouldn't be too many updates per-week (aside from probably the first time it runs).

That's true, even though NPM is moving quite quickly. Not sure about the python world

**Comment by nlsdfnbch** [comment]
>I guess CircleCI is pay-as-you-go and some of our tests are also quite heavy. So it's not only a technical question

Money should be the least of your concerns - especially if that saves you time manually testing a dependency upgrade. Chacnes are pretty good that the CI is cheaper than you.

>I am not sure if you can currently skip the ci on rebase, but there are
some issues in that regards open for dependabot.

I'm sure there's a sensible approach to allowing this somehow. But that can be discussed when we get to it.

**Comment by nlsdfnbch** [comment]
>That's true, even though NPM is moving quite quickly. Not sure about the python world

Ach right, you're silly JS people, I forgot :smiley: you can of course always fine-tune the timeframes. Asides from that, it's probably even more important because of that, to automate away as much as possible of this.

**Comment by kelsos** [comment]
> Ach right, you're silly JS people, I forgot smiley you can of course always fine-tune the timeframes. 

At heart, I am still an Android/Kotlin person, although I deal more with JS nowadays :P
But yes having an automated way to keep dependencies updated, ensuring that there is no breaking is really a time saver.

**Comment by nephix** [comment]
> you're silly JS people

Compliment taken

**Comment by palango** [comment]
This is implemented.
