### ISSUE TITLE
Add task to assert total balance

### ISSUE THREAD

**Issue by czepluch** [raiden-network/scenario-player#93]
Since we can't always know which path a mediated payment takes, when there are several path, we need a way to assert that balances are correctly updated. Currently we can also do so for a specific channel, but that isn't viable. 

So a task that combines all channel balances might be better to assert that a payment went through, when we don't care about which path was used.

**Comment by ulope** [comment]
Unless I’m misunderstanding this should be exactly what `assert_all` does.

**Comment by czepluch** [comment]
Could be. But then I am misunderstanding the `balances` part of `assert_all`, since I thought that these numbers had to be the correct balances of the channels.

`- assert_all: {from: 0, count: 2, balances: [10, 10], total_deposits: [10, 10], states: ['opened', 'opened']}`

If we don't know the paths used for mediated payments we also don't know the actual balances. But maybe I am misunderstanding how the assert works.

**Comment by ulope** [comment]
Ah so you basically want a multi-node version of `assert_sum`.

**Comment by czepluch** [comment]
If by multi-node you mean multi-channel, then yes. I want to see the total balance that I have in all open channels. If we have a diamond topology and one node sends to the "opposite" node, I don't know which path will be used and I don't care about it. I just want to know that the balance was updated. If that's what `assert_sum` already does, then we should add it to the example file, because I didn't know about it :P

**Comment by czepluch** [comment]
What I need already exists as Ulo mentioned with the `assert_sum`. Closing this
