### ISSUE TITLE
Node Management Service [STUB]

### ISSUE THREAD

**Issue by nlsdfnbch** [raiden-network/scenario-player#96]
# Domain of the Service
*Explicitly state the area of concern and operation for this service. If sensible, also state what it is explicitly NOT responible for.*

# Dependencies
*State services, processes or libraries this service requires to work correctly.*

# Endpoints
*Give a top-level overview of the endpoints expected to be present on the service. Link to `Service Blueprint Spec` issues for each endpoint.*

**Comment by palango** [comment]
Closing. See #495
